In [1]:
import pandas as pd
import os
import ast
import numpy as np
import pickle
from datetime import datetime

In [2]:
path = 'C:/Users/HEN1/Projects/YELP_DATASET/DATA'
file_name = 'yelp.pkl'
file = os.path.join(path, file_name)
with open(file, 'rb') as file:
    df=pickle.load(file)

In [3]:
df = df.drop(columns=['date', 'yelping_since'])

In [12]:
df[df['review_count']<10].shape[0]

4851

In [4]:
df.head()

user_id             business_id  stars postal_code  \
16  bUHweiErUJ36WGeNrPmEbA  6Hm2FmfLcU_M91TrZI5htA      5     V5L 3X5   
17  JHXQEayrDHOWGexs0dCviA  KXCXaF5qimmtKKqnPc_LQA      1     V6E 1A1   
22  vFnYYmtVwcMGyyGesNImVQ  jMz_y_-cWMfiZF7Q5snE6Q      5     V6E 2B1   
40  M20pTzUOo2yD5Cuh5shjSA  M4jkJHewQXZvDV34Tuon8g      1     V6K 1E9   
47  IMfkbLVt_GJfD7zJ9T4fcw  VPqWLp9kMiZEbctCebIZUA      3     V6B 3A4   

     latitude   longitude  business_stars  review_count is_open  Acai Bowls  \
16  49.272800 -123.069730             3.5           225       0           0   
17  49.284877 -123.122629             4.0           849       1           0   
22  49.287496 -123.128934             4.5           436       1           0   
40  49.270973 -123.155283             3.5           270       1           0   
47  49.280443 -123.117036             4.0          2302       1           0   

    ... RestaurantsAttire_formal RestaurantsPriceRange2_1.0  \
16  ...                        0                          0   
17  ...                        0                          0   
22  ...                        0                          0   
40  ...                        0                          0   
47  ...                        0                          0   

   RestaurantsPriceRange2_2.0 RestaurantsPriceRange2_3.0  \
16                          1                          0   
17                          1                          0   
22                          1                          0   
40                          1                          0   
47                          1                          0   

   RestaurantsPriceRange2_4.0 use_review_count useful funny cool is_elite  
16                          0               39     68    38   19        0  
17                          0               70    118    26   21        0  
22                          0               68     34    10   18        0  
40                          0                2      2     0    0        0  
47                          0               12      6     1    1        0  

[5 rows x 1234 columns]

In [5]:
trans_label = {1:0, 2:1, 3:2, 4:3, 5:4}
df['stars'] = df['stars'].map(trans_label)

In [6]:
df = df.loc[:,df.apply(pd.Series.nunique) != 1]

In [7]:
for col in df.columns.values.tolist():     
    print({col:df[col].unique()})

{'user_id': ['bUHweiErUJ36WGeNrPmEbA', 'JHXQEayrDHOWGexs0dCviA', 'vFnYYmtVwcMGyyGesNImVQ', 'M20pTzUOo2yD5Cuh5shjSA', 'IMfkbLVt_GJfD7zJ9T4fcw', ..., 'yMxIisZ-sNu3LZTUFfcG1Q', 'rVHLpERGB0wVjrG-MsacQQ', 'YTIlkSG3WwP63wLoWWp8-w', 'WZR8A9MOHDKMoOMiNV5NgQ', 'taIE-ZuhQVVKKaG82W_sRg']
Length: 85561
Categories (85561, object): ['--2mZKA9psrdip7ide8kUA', '--3l8wysfp49Z2TLnyT0vg', '--5-MQZPsn2CJkyMFQkOgQ', '--50YzjtBsdxOGVqTkvaKA', ..., 'zzmoLASeDvnSDvjy_4L0cQ', 'zzo--VpSQh8PpsGVeMC1dQ', 'zzorrjNvR0xJ8u175BF4NQ', 'zzspfziwYkiFeh50_3_96g']}
{'business_id': ['6Hm2FmfLcU_M91TrZI5htA', 'KXCXaF5qimmtKKqnPc_LQA', 'jMz_y_-cWMfiZF7Q5snE6Q', 'M4jkJHewQXZvDV34Tuon8g', 'VPqWLp9kMiZEbctCebIZUA', ..., 'HDw5Dqqwbcym7123exU1Sw', 'XDWS4Rayi52jrN0z0ibG4Q', 'Xs01zFimxlUjo_KqYwI_wg', 'YQ5nt_RTUqEdo0YkI0TNcg', 'SGJLq_sx67lPyXdFEZGXng']
Length: 4278
Categories (4278, object): ['--bbZa1KPYSmW0X4o3TUQw', '-0T2mO5-vM_cBN2cS92Mdw', '-0aOWWsqmzgF18V3PLPnRg', '-25EAANVLToVlw7yWhbjwA', ..., 'zwn53gHyn1NlX9h3jKFOUg', 'zyrXzq

{' Egyptian': [0, 1]
Categories (2, int64): [0, 1]}
{' Ethiopian': [0, 1]
Categories (2, int64): [0, 1]}
{' Ethnic Food': [0, 1]
Categories (2, int64): [0, 1]}
{' Ethnic Grocery': [0, 1]
Categories (2, int64): [0, 1]}
{' Event Planning & Services': [0, 1]
Categories (2, int64): [0, 1]}
{' Eyelash Service': [0, 1]
Categories (2, int64): [0, 1]}
{' Falafel': [0, 1]
Categories (2, int64): [0, 1]}
{' Fashion': [0, 1]
Categories (2, int64): [0, 1]}
{' Fast Food': [0, 1]
Categories (2, int64): [0, 1]}
{' Festivals': [0, 1]
Categories (2, int64): [0, 1]}
{' Filipino': [0, 1]
Categories (2, int64): [0, 1]}
{' Financial Services': [0, 1]
Categories (2, int64): [0, 1]}
{' Fish & Chips': [0, 1]
Categories (2, int64): [0, 1]}
{' Fitness & Instruction': [0, 1]
Categories (2, int64): [0, 1]}
{' Florists': [0, 1]
Categories (2, int64): [0, 1]}
{' Flowers & Gifts': [0, 1]
Categories (2, int64): [0, 1]}
{' Fondue': [0, 1]
Categories (2, int64): [0, 1]}
{' Food': [0, 1]
Categories (2, int64): [0, 1]}
{'

{' Tea Rooms': [0, 1]
Categories (2, int64): [0, 1]}
{' Team Building Activities': [0, 1]
Categories (2, int64): [0, 1]}
{' Tennis': [0, 1]
Categories (2, int64): [0, 1]}
{' Tex-Mex': [0, 1]
Categories (2, int64): [0, 1]}
{' Thai': [0, 1]
Categories (2, int64): [0, 1]}
{' Themed Cafes': [0, 1]
Categories (2, int64): [0, 1]}
{' Tiki Bars': [0, 1]
Categories (2, int64): [0, 1]}
{' Tobacco Shops': [0, 1]
Categories (2, int64): [0, 1]}
{' Tours': [0, 1]
Categories (2, int64): [0, 1]}
{' Towing': [0, 1]
Categories (2, int64): [0, 1]}
{' Trainers': [0, 1]
Categories (2, int64): [0, 1]}
{' Turkish': [0, 1]
Categories (2, int64): [0, 1]}
{' Ukrainian': [0, 1]
Categories (2, int64): [0, 1]}
{' Vape Shops': [0, 1]
Categories (2, int64): [0, 1]}
{' Vegan': [0, 1]
Categories (2, int64): [0, 1]}
{' Vegetarian': [0, 1]
Categories (2, int64): [0, 1]}
{' Venezuelan': [0, 1]
Categories (2, int64): [0, 1]}
{' Venues & Event Spaces': [0, 1]
Categories (2, int64): [0, 1]}
{' Videos & Video Game Rental': [

{'Professional Services': [0, 1]
Categories (2, int64): [0, 1]}
{'Public Services & Government': [0, 1]
Categories (2, int64): [0, 1]}
{'Pubs': [0, 1]
Categories (2, int64): [0, 1]}
{'Ramen': [0, 1]
Categories (2, int64): [0, 1]}
{'Restaurants': [1, 0]
Categories (2, int64): [0, 1]}
{'Salad': [0, 1]
Categories (2, int64): [0, 1]}
{'Sandwiches': [0, 1]
Categories (2, int64): [0, 1]}
{'Scandinavian': [0, 1]
Categories (2, int64): [0, 1]}
{'Seafood': [0, 1]
Categories (2, int64): [0, 1]}
{'Seafood Markets': [0, 1]
Categories (2, int64): [0, 1]}
{'Sewing & Alterations': [0, 1]
Categories (2, int64): [0, 1]}
{'Shared Office Spaces': [0, 1]
Categories (2, int64): [0, 1]}
{'Shaved Snow': [0, 1]
Categories (2, int64): [0, 1]}
{'Shopping': [0, 1]
Categories (2, int64): [0, 1]}
{'Shopping Centers': [0, 1]
Categories (2, int64): [0, 1]}
{'Singaporean': [0, 1]
Categories (2, int64): [0, 1]}
{'Smokehouse': [0, 1]
Categories (2, int64): [0, 1]}
{'Soup': [0, 1]
Categories (2, int64): [0, 1]}
{'Southe

In [8]:
# check lightgbm version
import lightgbm as lgb
print(lgb.__version__)

3.3.1


In [9]:
df.shape

(305531, 657)

In [10]:
x = df.drop(columns='stars')
y = df.stars

In [11]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.2)

In [12]:
x_train.head()

user_id             business_id postal_code  \
4722617  VGwJ7OpknZT6Qv9OCfzZaA  CFUGcrR9ccZ_dChqaPJEkw     V5T 3G2   
8125749  78UCe_x7ZlYKxdxf7ys1OQ  yi-RDRcclrW2mZ_84dkZdQ     V6P 4A8   
6950203  Usc6a4N8b2KAhei0V80vyg  yB24S-bsaJqaP3pQFpKpBw     V5T 1B4   
312418   k3zBiXtd0rv8n74VYNdUZw  w3HSOOqJednBOYbO3fajvQ     V5T 2R6   
2075711  tK9lJhkNy6MEsZcyedIwlw  b102gNXJjaOSsDc3G1ePTQ     V6E 3S7   

          latitude   longitude  business_stars  review_count is_open  \
4722617  49.259558 -123.100899             3.5            77       0   
8125749  49.210933 -123.130518             3.5           114       1   
6950203  49.269455 -123.107722             3.5           184       1   
312418   49.257281 -123.089767             4.0           413       1   
2075711  49.286981 -123.119496             3.5            72       1   

         Acai Bowls  Accessories  ... RestaurantsAttire_formal  \
4722617           0            0  ...                        0   
8125749           0            0  ...                        0   
6950203           0            0  ...                        0   
312418            0            0  ...                        0   
2075711           0            0  ...                        0   

        RestaurantsPriceRange2_1.0 RestaurantsPriceRange2_2.0  \
4722617                          0                          1   
8125749                          0                          1   
6950203                          0                          1   
312418                           0                          1   
2075711                          1                          0   

        RestaurantsPriceRange2_3.0 RestaurantsPriceRange2_4.0  \
4722617                          0                          0   
8125749                          0                          0   
6950203                          0                          0   
312418                           0                          0   
2075711                          0                          0   

        use_review_count useful funny cool is_elite  
4722617               18     20     7    7        0  
8125749              159     97    16   17        0  
6950203               43      6     5    7        0  
312418                59    325   357  152        0  
2075711              198    377   226  150        1  

[5 rows x 656 columns]

## Light GBM

In [13]:
train_data=lgb.Dataset(x_train,label=y_train)

In [14]:
param = {'objective': 'multiclass', 'learning_rate':.01, 'num_class':5, 'num_leaves':40, 'max_depth':6, 'force_col_wise':True}
param['metric'] = ['multi_logloss', 'multi_error']

In [15]:
num_round=100

In [16]:
start=datetime.now()
lgbm=lgb.train(param,train_data,num_round)
stop=datetime.now()

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Total Bins 23290
[LightGBM] [Info] Number of data points in the train set: 244424, number of used features: 566
[LightGBM] [Info] Start training from score -2.348907
[LightGBM] [Info] Start training from score -2.351396
[LightGBM] [Info] Start training from score -1.824834
[LightGBM] [Info] Start training from score -1.159811
[LightGBM] [Info] Start training from score -1.095116


In [17]:
ypred_lgbm=lgbm.predict(x_test)

In [18]:
ypred_lgbm = [np.argmax(line) for line in ypred_lgbm]

In [19]:
from sklearn.metrics import confusion_matrix, balanced_accuracy_score
print(confusion_matrix(y_test, ypred_lgbm))
print(balanced_accuracy_score(y_test, ypred_lgbm))

[[ 1189    33   108  1966  2623]
 [  381    48   347  2841  2140]
 [  242    45   631  5868  2994]
 [  290    25   405 10550  7987]
 [  327     6    44  5534 14483]]
0.3063496419736492


In [164]:
ypred_lgbm_train = lgbm.predict(x_train)
ypred_lgbm_train = [np.argmax(line) for line in ypred_lgbm_train]
print(balanced_accuracy_score(y_train, ypred_lgbm_train))

0.31411869236443757


## Naive Bayes

In [143]:
df_nostr = df.drop(columns=['user_id', 'business_id', 'postal_code'])

In [144]:
xn = df_nostr.drop(columns='stars')
yn = df_nostr.stars

In [145]:
from sklearn.model_selection import train_test_split 
xn_train,xn_test,yn_train,yn_test=train_test_split(xn,yn,test_size=.3)

In [146]:
xn_train.head()

latitude   longitude  business_stars  review_count is_open  \
1961085  49.276233 -123.125026             4.0           120       0   
8413448  49.246462 -123.101442             4.5           209       1   
6046794  49.282006 -123.123025             4.0           217       1   
3076872  49.290630 -123.137060             4.5           845       1   
4630005  49.263078 -123.121005             3.5            35       0   

         Acai Bowls  Accessories  Accountants  Active Life  Acupuncture  ...  \
1961085           0            0            0            0            0  ...   
8413448           0            0            0            0            0  ...   
6046794           0            0            0            0            0  ...   
3076872           0            0            0            0            0  ...   
4630005           0            0            0            0            0  ...   

        RestaurantsAttire_formal RestaurantsPriceRange2_1.0  \
1961085                        0                          0   
8413448                        0                          1   
6046794                        0                          1   
3076872                        0                          0   
4630005                        0                          1   

        RestaurantsPriceRange2_2.0 RestaurantsPriceRange2_3.0  \
1961085                          1                          0   
8413448                          0                          0   
6046794                          0                          0   
3076872                          1                          0   
4630005                          0                          0   

        RestaurantsPriceRange2_4.0 use_review_count useful funny cool is_elite  
1961085                          0              267    672   188  259        1  
8413448                          0                7      0     0    0        0  
6046794                          0               89    162    52   80        1  
3076872                          0               98     64    10   16        1  
4630005                          0               58    161    16   36        0  

[5 rows x 1230 columns]

In [147]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB().fit(xn_train, yn_train)
ypred_gnb = gnb.predict(xn_test)

In [148]:
# accuracy on X_test
accuracy = gnb.score(xn_test, yn_test)
print(f"accuracy for baive bayes: {accuracy}")
 
# creating a confusion matrix
cm_nb = confusion_matrix(yn_test, ypred_gnb)
print(cm_nb)

accuracy for baive bayes: 0.29101025529129393
[[ 4285  1278   693   798  1843]
 [ 3068  1500  1146   917  2129]
 [ 4025  2350  2513  2129  3707]
 [ 7080  3748  3897  4967  8843]
 [ 7133  3044  2403  4755 13409]]


## KNN

In [149]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5).fit(xn_train, yn_train)

In [152]:
'''
# accuracy on X_test
accuracy = knn.score(xn_test, yn_test)
print(f"accuracy for knn: {accuracy}")
 
# creating a confusion matrix
knn_predictions = knn.predict(xn_test)
cm_knn = confusion_matrix(yn_test, knn_predictions)
print(cm_nb)
'''

'\n# accuracy on X_test\naccuracy = knn.score(xn_test, yn_test)\nprint(f"accuracy for knn: {accuracy}")\n \n# creating a confusion matrix\nknn_predictions = knn.predict(xn_test)\ncm_knn = confusion_matrix(yn_test, knn_predictions)\nprint(cm_nb)\n'